package Main;

import Other.HighScore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

public class WelcomeScreen extends javax.swing.JFrame {

    protected boolean soundOn;
    protected int difficulty;

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
        soundOn = true;
        difficulty = 1;
        optionBoard = new OptionBoard(1, true);
        scoreBoard = new ScoreBoard();

        tfPlayer1Name.setText(System.getProperty("user.name"));
        tfPlayer2Name.setText(System.getProperty("user.name"));

        bDualPlayer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                bDualPlayerActionPerformed(e);
            }
        });
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                scoreBoard.writeHighScore();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSinglePlayer = new javax.swing.JButton();
        bDualPlayer = new javax.swing.JButton();
        bLoad = new javax.swing.JButton();
        bHighScore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bOption = new javax.swing.JButton();
        tfPlayer1Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPlayer2Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Asteroid Game");
        setResizable(false);

        bSinglePlayer.setText("Single Player");
        bSinglePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSinglePlayerActionPerformed(evt);
            }
        });

        bDualPlayer.setText("Dual Player");

        bLoad.setText("Load Saved Game");
        bLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadActionPerformed(evt);
            }
        });

        bHighScore.setText("Show High Score");
        bHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHighScoreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("The Asteroid Game");

        bOption.setText("Option");
        bOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOptionActionPerformed(evt);
            }
        });

        tfPlayer1Name.setText("jTextField1");

        jLabel2.setText("Your name:");

        jLabel3.setText("Your name:");

        tfPlayer2Name.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bHighScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bDualPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPlayer2Name))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSinglePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSinglePlayer)
                    .addComponent(tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDualPlayer)
                    .addComponent(jLabel3)
                    .addComponent(tfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHighScore)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSinglePlayerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        GameScreen game = new GameScreen(this, GameScreen.SINGLE_PLAYER_MODE, scoreBoard.getHighScoreTable());
        game.runGame();
    }

    private void bDualPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSinglePlayerActionPerformed
        this.setVisible(false);
        GameScreen game = new GameScreen(this, GameScreen.DUAL_PLAYER_MODE, scoreBoard.getHighScoreTable());
        game.runGame();
    }//GEN-LAST:event_bSinglePlayerActionPerformed

private void bLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadActionPerformed
    // TODO add your handling code here:
    JFileChooser chooser = new JFileChooser();
    int choose;
    chooser.setApproveButtonText("Load Game");
    choose = chooser.showOpenDialog(this);
    if (choose == JFileChooser.APPROVE_OPTION) {
        loadGame(chooser.getSelectedFile());
    }

}//GEN-LAST:event_bLoadActionPerformed

    private void loadGame(File file) {
        GameScreen game = new GameScreen(this, GameScreen.SINGLE_PLAYER_MODE, scoreBoard.getHighScoreTable());
        game.load(file);
    }

    public void updateHighScore(HighScore newHighScore) {
        if (newHighScore.getScore() <= 0) {
            return;
        }
        for (int i = 0; i < scoreBoard.highScore.size(); i++) {
            if (newHighScore.getScore() >= scoreBoard.highScore.get(i).getScore()) {
                scoreBoard.highScore.add(i, newHighScore);
                return;
            }
        }
        scoreBoard.highScore.add(newHighScore);
    }

private void bHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHighScoreActionPerformed
    // TODO add your handling code here:
    this.setVisible(false);
    scoreBoard.updateScoreBoard();
    scoreBoard.setVisible(true);
}//GEN-LAST:event_bHighScoreActionPerformed

private void bOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOptionActionPerformed
    // TODO add your handling code here:
    this.setVisible(false);
    optionBoard.setVisible(true);
}//GEN-LAST:event_bOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                WelcomeScreen welcome = new WelcomeScreen();
                welcome.optionBoard.setWelcomeScreen(welcome);
                welcome.scoreBoard.setWelcomeScreen(welcome);
                welcome.setVisible(true);
            }
        });
    }
    private OptionBoard optionBoard;
    private ScoreBoard scoreBoard;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDualPlayer;
    private javax.swing.JButton bHighScore;
    private javax.swing.JButton bLoad;
    private javax.swing.JButton bOption;
    private javax.swing.JButton bSinglePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JTextField tfPlayer1Name;
    protected javax.swing.JTextField tfPlayer2Name;
    // End of variables declaration//GEN-END:variables
}
